-- MySQL Script generated by MySQL Workbench
-- 03/18/17 21:42:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_shop` DEFAULT CHARACTER SET UTF8 ;
USE `online_shop` ;

-- -----------------------------------------------------
-- Table `online_shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`clients` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(50) NOT NULL,
  `c_surname` VARCHAR(50) NOT NULL,
  `c_email` VARCHAR(45) NOT NULL,
  `c_password` CHAR(64) NOT NULL,
  `c_phonenumber` VARCHAR(20) NOT NULL,
  `c_balance` DOUBLE NOT NULL DEFAULT 0,
  `discount_coefficient` DOUBLE NOT NULL DEFAULT 0,
  `c_banned` TINYINT(1) NOT NULL DEFAULT 0,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `c_imgurl` VARCHAR(45) NOT NULL DEFAULT 'img/users/default_avatar.jpg',
  `c_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`categories` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`products` (
  `p_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_title` VARCHAR(45) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `p_price` DOUBLE NOT NULL,
  `p_description` MEDIUMTEXT NOT NULL,
  `p_amount` INT(11) NOT NULL,
  `p_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `p_imgurl` VARCHAR(100) NOT NULL DEFAULT 'img/products/img_unavailable.jpg',
  PRIMARY KEY (`p_id`),
  INDEX `fk_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_shop`.`categories` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`orders` (
  `o_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_id` INT(11) NOT NULL,
  `o_order_date` DateTime  NULL,
  `o_delivery_date` DateTime  NULL,
  `o_address` VARCHAR(100) NOT NULL,
  `o_bill` DOUBLE NOT NULL,
  `o_discount` DOUBLE NOT NULL,
  `o_total` DOUBLE NOT NULL,
  `o_ispaid` TINYINT(1) NOT NULL DEFAULT 0,
  `o_iscompleted` TINYINT(1) NOT NULL DEFAULT 0,
  `o_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`o_id`),
  INDEX `fk_clients_orders_idx` (`c_id` ASC),
  CONSTRAINT `fk_clients_orders`
    FOREIGN KEY (`c_id`)
    REFERENCES `online_shop`.`clients` (`c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`ordered_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`ordered_products` (
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_quantity` INT(11) NOT NULL,
  INDEX `fk_goods_op_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_op`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`products` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_op`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_shop`.`orders` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `online_shop`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Home Stuff');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Electronics');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Clothes');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Shoes');

COMMIT;

-- -----------------------------------------------------
-- Data for table `online_shop`.`products`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Coffee Table', 1, 5.95, 'White coffee Table', 20);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'IHelper', 2, 5.00, 'Smart house hub', 35);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Alpha Swing', 3, 10.00, 'T-Shirt', 50);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Dr. Martens x', 4, 65.45, 'Leather boots', 20);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'RetroPlain', 1, 7.20, 'Ikea chair', 60);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'MyWatch', 2, 35.20, 'Electronic watch', 45);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'UFit', 2, 101.20, 'Fitness bracelet', 45);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Converse t-Edition', 4, 82.20, 'Men shoes', 0);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'TabletR', 2, 110.20, 'Tablet for buisnes', 10);

COMMIT;

-- -----------------------------------------------------
-- Data for table `online_shop`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_balance`, `c_banned`, `is_admin`) VALUES (DEFAULT, 'Jim', 'Moore', 'jmoor@gmail.com', 'f6e0a1e2ac41945a9aa7ff8a8aaa0cebc12a3bcc981a929ad5cf810a090e11ae', '+375 (29) 312-31-31', 0, 0, 0);
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_balance`, `c_banned`, `is_admin`) VALUES (DEFAULT, 'Mike', 'Door', 'miked@gmail.com', '9b871512327c09ce91dd649b3f96a63b7408ef267c8cc5710114e629730cb61f', '+375 (25) 246-85-76', 200, 0, 1);

COMMIT;




