-- MySQL Script generated by MySQL Workbench
-- 03/18/17 21:42:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_shop` DEFAULT CHARACTER SET UTF8 ;
USE `online_shop` ;

-- -----------------------------------------------------
-- Table `online_shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`clients` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(50) NOT NULL,
  `c_surname` VARCHAR(50) NOT NULL,
  `c_email` VARCHAR(45) NOT NULL,
  `c_password` CHAR(64) NOT NULL,
  `c_phonenumber` VARCHAR(20) NOT NULL,
  `c_balance` DOUBLE NOT NULL DEFAULT 0,
  `c_isbanned` TINYINT(1) NOT NULL DEFAULT 0,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `c_imgurl` VARCHAR(45) NULL,
  `c_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`discounts` (
  `c_id` INT(11) NOT NULL,
  `discount_coefficient` DOUBLE NOT NULL,
  INDEX `fk_discounts_clients` (`c_id` ASC),
  PRIMARY KEY (`c_id`),
  CONSTRAINT `fk_discounts_clients`
    FOREIGN KEY (`c_id`)
    REFERENCES `online_shop`.`clients` (`c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`categories` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`products` (
  `p_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_title` VARCHAR(45) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `p_price` DOUBLE NOT NULL,
  `p_description` MEDIUMTEXT NOT NULL,
  `p_amount` INT(11) NOT NULL,
  `p_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `p_imgurl` VARCHAR(100) NULL,
  PRIMARY KEY (`p_id`),
  INDEX `fk_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_shop`.`categories` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`orders` (
  `o_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_id` INT(11) NOT NULL,
  `o_order_date` TIMESTAMP NULL,
  `o_delivery_date` TIMESTAMP NULL,
  `o_address` VARCHAR(100) NOT NULL,
  `o_bill` DOUBLE NOT NULL,
  `o_discount` DOUBLE NOT NULL,
  `o_total` DOUBLE NOT NULL,
  `o_ispaid` TINYINT(1) NOT NULL DEFAULT 0,
  `o_iscompleted` TINYINT(1) NOT NULL DEFAULT 0,
  `o_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`o_id`),
  INDEX `fk_clients_orders_idx` (`c_id` ASC),
  CONSTRAINT `fk_clients_orders`
    FOREIGN KEY (`c_id`)
    REFERENCES `online_shop`.`clients` (`c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;


-- -----------------------------------------------------
-- Table `online_shop`.`ordered_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`ordered_products` (
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_quantity` INT(11) NOT NULL,
  INDEX `fk_goods_op_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_op`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`products` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_op`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_shop`.`orders` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `online_shop`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Home Stuff');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Electronics');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Clothes');
INSERT INTO `online_shop`.`categories` (`c_id`, `category`) VALUES (DEFAULT, 'Shoes');

COMMIT;

-- -----------------------------------------------------
-- Data for table `online_shop`.`products`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Cleaner', 1, 5.95, 'Detergent ', 20);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Remote GT', 2, 5.00, 'TV Remote', 35);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'PunkShirt', 3, 10.00, 'T-Shirt', 50);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Dr. Martens x', 4, 65.45, 'Leather boots', 20);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'SoftSkin', 1, 7.20, 'Towel', 60);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'MyWatch', 2, 35.20, 'Electronic watch', 45);
INSERT INTO `online_shop`.`products` (`p_id`, `p_title`, `category_id`, `p_price`, `p_description`, `p_amount`) VALUES (DEFAULT, 'Converse t-Edition', 4, 82.20, 'Men shoes', 0);

COMMIT;

-- -----------------------------------------------------
-- Data for table `online_shop`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_balance`, `c_isbanned`, `is_admin`) VALUES (DEFAULT, 'Jim', 'Moore', 'jmoor@gmail.com', 'f6e0a1e2ac41945a9aa7ff8a8aaa0cebc12a3bcc981a929ad5cf810a090e11ae', '23457', 200, 0, 0);
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_balance`, `c_isbanned`, `is_admin`) VALUES (DEFAULT, 'Mike', 'Door', 'miked@gmail.com', '9b871512327c09ce91dd649b3f96a63b7408ef267c8cc5710114e629730cb61f', '25254', 200, 0, 1);
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_isbanned`, `is_admin`) VALUES (DEFAULT, 'Dave', 'Wright', 'dwr@tut.by', '556d7dc3a115356350f1f9910b1af1ab0e312d4b3e4fc788d2da63668f36d017', '58754', 1, 0);
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_isbanned`, `is_admin`) VALUES (DEFAULT, 'Joe', 'Bing', 'fr@ya.ru', '3538a1ef2e113da64249eea7bd068b585ec7ce5df73b2d1e319d8c9bf47eb314', '24587', 0, 0);
INSERT INTO `online_shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`, `c_phonenumber`, `c_isbanned`, `is_admin`) VALUES (DEFAULT, 'Bill', 'Flint', 'bf@gmail.com', '2926a2731f4b312c08982cacf8061eb14bf65c1a87cc5d70e864e079c6220731', '97644', 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `online_shop`.`discounts`
-- -----------------------------------------------------
START TRANSACTION;
USE `online_shop`;
INSERT INTO `online_shop`.`discounts` (`c_id`, `discount_coefficient`) VALUES (2, 0.1);
INSERT INTO `online_shop`.`discounts` (`c_id`, `discount_coefficient`) VALUES (4, 0.2);
INSERT INTO `online_shop`.`discounts` (`c_id`, `discount_coefficient`) VALUES (5, 0.05);
INSERT INTO `online_shop`.`discounts` (`c_id`, `discount_coefficient`) VALUES (1, 0.01);

COMMIT;


